name: AnvilCombineChecker
version: ${project.version}
main: megacrafter10.combinechecker.AnvilCombineChecker
authors: [MegaCrafter10]
description: Only allow compatible enchantments to be combined into books
